//
// Created by Philip on 6/1/2020.
//

#ifndef SOCIETY_MACROS_H
#define SOCIETY_MACROS_H

#include <memory>
#include <string>
#include <utility>
#include <vector>


#define POINTERIZE(CLASS) typedef std::shared_ptr<CLASS> Ptr
#define SP(X) std::shared_ptr<X>
#define EMPTY
#define MOVE(X) std::move(X)
#define NOOP(...)
#define ID(X) X

// Base getter/setter
#define GETFUNC(NAME, TYPE, ACCESS, PRE, PREFIX, POST) ACCESS: PRE TYPE PREFIX##_##NAME() POST { return _##NAME; }
#define SETFUNC(NAME, TYPE, ACCESS, PRE, PREFIX, VALUE_MOD) ACCESS: PRE void PREFIX##_##NAME(TYPE val) { _##NAME = VALUE_MOD(val); }

// Useful Getter/Setter permutations
#define GET(NAME, TYPE, ACCESS) GETFUNC(NAME, TYPE, ACCESS, inline, get, EMPTY)
#define GET_BOOL(NAME, _, ACCESS) GETFUNC(NAME, bool, ACCESS, inline, is,  EMPTY)
#define SET(NAME, TYPE, ACCESS) SETFUNC(NAME, TYPE, ACCESS, inline, set, ID)
#define MOVE_AND_SET(NAME, TYPE, ACCESS) SETFUNC(NAME, TYPE, ACCESS, inline, set, MOVE)
#define GET_REF(NAME, TYPE, ACCESS) GETFUNC(NAME, TYPE, ACCESS, inline, &get, EMPTY)
#define SET_REF(NAME, TYPE, ACCESS) SETFUNC(NAME, TYPE##&, ACCESS, inline, set, ID)

// Private var base
#define _DECLARE(NAME, TYPE, ACCESS) ACCESS: TYPE _##NAME
#define _DECLARE_INIT(NAME, TYPE, ACCESS, DEFAULT) ACCESS: TYPE _##NAME{DEFAULT}
#define _VAR(NAME, TYPE, GETTER, GET_ACCESS, SETTER, SET_ACCESS) _DECLARE(NAME, TYPE, private); GETTER(NAME, TYPE, GET_ACCESS) SETTER(NAME, TYPE, SET_ACCESS)
#define _VAR_INIT(NAME, TYPE, DEFAULT, GETTER, GET_ACCESS, SETTER, SET_ACCESS) _DECLARE_INIT(NAME, TYPE, private, DEFAULT); GETTER(NAME, TYPE, GET_ACCESS) SETTER(NAME, TYPE, SET_ACCESS)

// CONSTVAR: const var
#define _CONSTVAR(NAME, TYPE, ACCESS) _DECLARE(NAME, const TYPE, private); GET(NAME, TYPE, ACCESS)
#define _CONSTVAR_INIT(NAME, TYPE, ACCESS, DEFAULT) _DECLARE_INIT(NAME, const TYPE, private, DEFAULT); GET(NAME, TYPE, ACCESS)

// Useful permutations of var base
#define _VAR_GET(NAME, TYPE, ACCESS) _VAR(NAME, TYPE, GET, ACCESS, NOOP, EMPTY)
#define _VAR_GET_INIT(NAME, TYPE, ACCESS, DEFAULT) _VAR_INIT(NAME, TYPE, DEFAULT, GET, ACCESS, NOOP, EMPTY)
#define _VAR_SET(NAME, TYPE, ACCESS) _VAR(NAME, TYPE, NOOP, EMPTY, SET, ACCESS)
#define _VAR_SET_INIT(NAME, TYPE, ACCESS, DEFAULT) _VAR_INIT(NAME, TYPE, DEFAULT, NOOP, EMPTY, SET, ACCESS)
#define _VAR_GETSET(NAME, TYPE, GET_ACCESS, SET_ACCESS) _VAR(NAME, TYPE, GET, GET_ACCESS, SET, SET_ACCESS)
#define _VAR_GETSET_INIT(NAME, TYPE, GET_ACCESS, SET_ACCESS, DEFAULT) _VAR_INIT(NAME, TYPE, DEFAULT, GET, GET_ACCESS, SET, SET_ACCESS)

// BVAR: boolean var gets use "isX" instead of "getX"
#define _BVAR_GETSET(NAME, GET_ACCESS, SET_ACCESS) _VAR(NAME, bool, GET_BOOL, GET_ACCESS, SET, SET_ACCESS)
#define _BVAR_GETSET_INIT(NAME, GET_ACCESS, SET_ACCESS, DEFAULT) _VAR_INIT(NAME, bool, DEFAULT, GET_BOOL, GET_ACCESS, SET, SET_ACCESS)
#define _BVAR_GET(NAME, ACCESS) _VAR(NAME, bool, GET_BOOL, ACCESS, NOOP, EMPTY)
#define _BVAR_GET_INIT(NAME, ACCESS, DEFAULT) _VAR_INIT(NAME, bool, DEFAULT, GET_BOOL, ACCESS, NOOP, EMPTY)

// MVAR: var that gets moved on set
#define _MVAR_SET(NAME, TYPE, ACCESS) _VAR(NAME, TYPE, NOOP, EMPTY, MOVE_AND_SET, ACCESS)
#define _MVAR_SET_INIT(NAME, TYPE, ACCESS, DEFAULT) _VAR_INIT(NAME, TYPE, DEFAULT, NOOP, EMPTY, MOVE_AND_SET, ACCESS)
#define _MVAR_GETSET(NAME, TYPE, GET_ACCESS, SET_ACCESS) _VAR(NAME, TYPE, GET, GET_ACCESS, MOVE_AND_SET, SET_ACCESS)
#define _MVAR_GETSET_INIT(NAME, TYPE, GET_ACCESS, SET_ACCESS, DEFAULT) _VAR_INIT(NAME, TYPE, DEFAULT, GET, GET_ACCESS, MOVE_AND_SET, SET_ACCESS)

// REFVAR: var that is moved with refs
#define _REFVAR_GET(NAME, TYPE, ACCESS) _VAR(NAME, TYPE, GET_REF, ACCESS, NOOP, EMPTY)
#define _REFVAR_GET_INIT(NAME, TYPE, ACCESS, DEFAULT) _VAR_INIT(NAME, TYPE, DEFAULT, GET_REF, ACCESS, NOOP, EMPTY)
#define _REFVAR_SET(NAME, TYPE, ACCESS) _VAR(NAME, TYPE, NOOP, EMPTY, SET_REF, ACCESS)
#define _REFVAR_SET_INIT(NAME, TYPE, ACCESS, DEFAULT) _VAR_INIT(NAME, TYPE, DEFAULT, NOOP, EMPTY, SET_REF, ACCESS)
#define _REFVAR_GETSET(NAME, TYPE, GET_ACCESS, SET_ACCESS) _VAR(NAME, TYPE, GET_REF, GET_ACCESS, SET_REF, SET_ACCESS)
#define _REFVAR_GETSET_INIT(NAME, TYPE, GET_ACCESS, SET_ACCESS, DEFAULT) _VAR_INIT(NAME, TYPE, DEFAULT, GET_REF, GET_ACCESS, SET_REF, SET_ACCESS)


#endif //SOCIETY_MACROS_H
